# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\spring22\SBEN311\TASKSS\task#4\Interpolation-Curve-Fitting-App\GUINew.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Slider(QtWidgets.QSlider):
    def mousePressEvent(self, event):
        super(Slider, self).mousePressEvent(event)
        if event.button() == QtCore.Qt.LeftButton:
            val = self.pixelPosToRangeValue(event.pos())
            self.setValue(val)

    def pixelPosToRangeValue(self, pos):
        opt = QtWidgets.QStyleOptionSlider()
        self.initStyleOption(opt)
        gr = self.style().subControlRect(QtWidgets.QStyle.CC_Slider, opt, QtWidgets.QStyle.SC_SliderGroove, self)
        sr = self.style().subControlRect(QtWidgets.QStyle.CC_Slider, opt, QtWidgets.QStyle.SC_SliderHandle, self)

        if self.orientation() == QtCore.Qt.Horizontal:
            sliderLength = sr.width()
            sliderMin = gr.x()
            sliderMax = gr.right() - sliderLength + 1
        else:
            sliderLength = sr.height()
            sliderMin = gr.y()
            sliderMax = gr.bottom() - sliderLength + 1;
        pr = pos - sr.center() + sr.topLeft()
        p = pr.x() if self.orientation() == QtCore.Qt.Horizontal else pr.y()
        return QtWidgets.QStyle.sliderValueFromPosition(self.minimum(), self.maximum(), p - sliderMin,
                                               sliderMax - sliderMin, opt.upsideDown)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1304, 738)
        MainWindow.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.latexEquationComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.latexEquationComboBox.setStyleSheet("border-radius: 7px;\n"
"padding: 5px;\n"
"background-color: rgb(47, 47, 47);")
        self.latexEquationComboBox.setObjectName("latexEquationComboBox")
        self.gridLayout_4.addWidget(self.latexEquationComboBox, 0, 1, 1, 1)
        self.latexEquationLabel = QtWidgets.QLabel(self.centralwidget)
        self.latexEquationLabel.setStyleSheet("background-color: rgb(163, 162, 168);\n"
"border-radius: 7px;\n"
"padding: 5px;")
        self.latexEquationLabel.setText("")
        self.latexEquationLabel.setObjectName("latexEquationLabel")
        self.gridLayout_4.addWidget(self.latexEquationLabel, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.gridLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.mainGraphGraphicsView = PlotWidget(self.gridLayoutWidget)
        self.mainGraphGraphicsView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.mainGraphGraphicsView.setObjectName("mainGraphGraphicsView")
        self.gridLayout_6.addWidget(self.mainGraphGraphicsView, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(700, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 2, 0, 1, 1)
        self.mainGraphLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.mainGraphLabel.setFont(font)
        self.mainGraphLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainGraphLabel.setObjectName("mainGraphLabel")
        self.gridLayout_6.addWidget(self.mainGraphLabel, 0, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.errorMapGridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.errorMapGridLayout.setContentsMargins(0, 0, 0, 0)
        self.errorMapGridLayout.setObjectName("errorMapGridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(2, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.errorMapGridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        # spacerItem2 = QtWidgets.QSpacerItem(550, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        # self.errorMapGridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.errorMapGraphicsView = PlotWidget(self.layoutWidget)
        self.errorMapGraphicsView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.errorMapGraphicsView.setObjectName("errorMapGraphicsView")
        self.errorMapGridLayout.addWidget(self.errorMapGraphicsView, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.splitter, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.errorMapControlsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.errorMapControlsGroupBox.sizePolicy().hasHeightForWidth())
        self.errorMapControlsGroupBox.setSizePolicy(sizePolicy)
        self.errorMapControlsGroupBox.setStyleSheet("QGroupBox {\n"
"border: 1.2px solid #ffffff;\n"
"border-radius: 2px;\n"
"    font: 10pt \"Georgia\";\n"
"    background-color: rgb(47, 47, 47);\n"
"}")
        self.errorMapControlsGroupBox.setObjectName("errorMapControlsGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.errorMapControlsGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.xAxisAndYAxisGridLayout = QtWidgets.QGridLayout()
        self.xAxisAndYAxisGridLayout.setObjectName("xAxisAndYAxisGridLayout")
        self.xAxisLabel = QtWidgets.QLabel(self.errorMapControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.xAxisLabel.setFont(font)
        self.xAxisLabel.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.xAxisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xAxisLabel.setObjectName("xAxisLabel")
        self.xAxisAndYAxisGridLayout.addWidget(self.xAxisLabel, 0, 0, 1, 1)
        self.xAxisComboBox = QtWidgets.QComboBox(self.errorMapControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.xAxisComboBox.setFont(font)
        self.xAxisComboBox.setStyleSheet("border-radius: 7px;\n"
"padding: 5px;")
        self.xAxisComboBox.setObjectName("xAxisComboBox")
        self.xAxisComboBox.addItem("")
        self.xAxisComboBox.addItem("")
        self.xAxisComboBox.addItem("")
        self.xAxisComboBox.addItem("")
        self.xAxisAndYAxisGridLayout.addWidget(self.xAxisComboBox, 0, 2, 1, 1)
        self.startAndCancelErrorMapPushButton = QtWidgets.QPushButton(self.errorMapControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.startAndCancelErrorMapPushButton.setFont(font)
        self.startAndCancelErrorMapPushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(25, 26, 30);\n"
"    border: 1.1px grey;\n"
"    border-radius: 1.5px;\n"
"    border-style: outset;\n"
"    background-color: rgb(163, 162, 168);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(145, 144, 149);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(118, 118, 112);\n"
"    }")
        self.startAndCancelErrorMapPushButton.setObjectName("startAndCancelErrorMapPushButton")
        self.xAxisAndYAxisGridLayout.addWidget(self.startAndCancelErrorMapPushButton, 3, 0, 1, 1)
        self.constantParameterLabel = QtWidgets.QLabel(self.errorMapControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.constantParameterLabel.setFont(font)
        self.constantParameterLabel.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.constantParameterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.constantParameterLabel.setObjectName("constantParameterLabel")
        self.xAxisAndYAxisGridLayout.addWidget(self.constantParameterLabel, 2, 0, 1, 1)
        self.yAxisLabel = QtWidgets.QLabel(self.errorMapControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.yAxisLabel.setFont(font)
        self.yAxisLabel.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.yAxisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yAxisLabel.setObjectName("yAxisLabel")
        self.xAxisAndYAxisGridLayout.addWidget(self.yAxisLabel, 1, 0, 1, 1)
        self.constantParameterSpinBox = QtWidgets.QSpinBox(self.errorMapControlsGroupBox)
        self.constantParameterSpinBox.setStyleSheet("border-radius: 7px;\n"
"padding: 5px;")
        self.constantParameterSpinBox.setObjectName("constantParameterSpinBox")
        self.xAxisAndYAxisGridLayout.addWidget(self.constantParameterSpinBox, 2, 2, 1, 1)
        self.yAxisComboBox = QtWidgets.QComboBox(self.errorMapControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.yAxisComboBox.setFont(font)
        self.yAxisComboBox.setStyleSheet("border-radius: 7px;\n"
"padding: 5px;")
        self.yAxisComboBox.setObjectName("yAxisComboBox")
        self.yAxisComboBox.addItem("")
        self.yAxisComboBox.addItem("")
        self.yAxisComboBox.addItem("")
        self.yAxisComboBox.addItem("")
        self.xAxisAndYAxisGridLayout.addWidget(self.yAxisComboBox, 1, 2, 1, 1)
        self.pauseAndResumeErrorMapPushButton = QtWidgets.QPushButton(self.errorMapControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pauseAndResumeErrorMapPushButton.setFont(font)
        self.pauseAndResumeErrorMapPushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(25, 26, 30);\n"
"    border: 1.1px grey;\n"
"    border-radius: 1.5px;\n"
"    border-style: outset;\n"
"    background-color: rgb(163, 162, 168);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(145, 144, 149);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(118, 118, 112);\n"
"    }")
        self.pauseAndResumeErrorMapPushButton.setObjectName("pauseAndResumeErrorMapPushButton")
        self.xAxisAndYAxisGridLayout.addWidget(self.pauseAndResumeErrorMapPushButton, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.xAxisAndYAxisGridLayout)
        self.errorMapProgressBar = QtWidgets.QProgressBar(self.errorMapControlsGroupBox)
        self.errorMapProgressBar.setStyleSheet("QProgressBar\n"
"{\n"
"border: solid grey;\n"
"border-radius: 5px;\n"
"color: black;\n"
"}\n"
"QProgressBar::chunk \n"
"{\n"
"background-color: rgb(163, 162, 168);\n"
"border-radius :5px;\n"
"} ")
        self.errorMapProgressBar.setProperty("value", 24)
        self.errorMapProgressBar.setObjectName("errorMapProgressBar")
        self.verticalLayout_2.addWidget(self.errorMapProgressBar)
        self.gridLayout.addWidget(self.errorMapControlsGroupBox, 0, 2, 1, 1)
        self.mainGraphControlsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.mainGraphControlsGroupBox.setStyleSheet("QGroupBox {\n"
"border: 1.2px solid #ffffff;\n"
"border-radius: 2px;\n"
"    font: 10pt \"Georgia\";\n"
"    background-color: rgb(47, 47, 47);\n"
"}")
        self.mainGraphControlsGroupBox.setObjectName("mainGraphControlsGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mainGraphControlsGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.signalCoveragePrecentageLabel = QtWidgets.QLabel(self.mainGraphControlsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signalCoveragePrecentageLabel.sizePolicy().hasHeightForWidth())
        self.signalCoveragePrecentageLabel.setSizePolicy(sizePolicy)
        self.signalCoveragePrecentageLabel.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.signalCoveragePrecentageLabel.setObjectName("signalCoveragePrecentageLabel")
        self.gridLayout_2.addWidget(self.signalCoveragePrecentageLabel, 2, 2, 1, 1)
        self.precentageOfErrorLabel = QtWidgets.QLabel(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.precentageOfErrorLabel.setFont(font)
        self.precentageOfErrorLabel.setStyleSheet("background-color: rgb(47, 47, 47);\n"
"")
        self.precentageOfErrorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.precentageOfErrorLabel.setObjectName("precentageOfErrorLabel")
        self.gridLayout_2.addWidget(self.precentageOfErrorLabel, 0, 0, 1, 1)
        self.extrapolationLabel = QtWidgets.QLabel(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.extrapolationLabel.setFont(font)
        self.extrapolationLabel.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.extrapolationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.extrapolationLabel.setObjectName("extrapolationLabel")
        self.gridLayout_2.addWidget(self.extrapolationLabel, 1, 0, 1, 1)
        self.extrapolationHorizontalSlider = Slider(self.mainGraphControlsGroupBox)
        self.extrapolationHorizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: white;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background-color:rgb(170,170,178);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.extrapolationHorizontalSlider.setMaximum(100)
        self.extrapolationHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.extrapolationHorizontalSlider.setObjectName("extrapolationHorizontalSlider")
        self.gridLayout_2.addWidget(self.extrapolationHorizontalSlider, 1, 1, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(50, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 2, 3, 1, 1)
        self.precentageOfErrorLcdNumber = QtWidgets.QLCDNumber(self.mainGraphControlsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.precentageOfErrorLcdNumber.sizePolicy().hasHeightForWidth())
        self.precentageOfErrorLcdNumber.setSizePolicy(sizePolicy)
        self.precentageOfErrorLcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.precentageOfErrorLcdNumber.setObjectName("precentageOfErrorLcdNumber")
        self.gridLayout_2.addWidget(self.precentageOfErrorLcdNumber, 0, 1, 1, 1)
        self.CurveFittingCoveragePrecentageLcdNumber = QtWidgets.QLCDNumber(self.mainGraphControlsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.CurveFittingCoveragePrecentageLcdNumber.sizePolicy().hasHeightForWidth())
        self.CurveFittingCoveragePrecentageLcdNumber.setSizePolicy(sizePolicy)
        self.CurveFittingCoveragePrecentageLcdNumber.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.CurveFittingCoveragePrecentageLcdNumber.setFocusPolicy(QtCore.Qt.NoFocus)
        self.CurveFittingCoveragePrecentageLcdNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CurveFittingCoveragePrecentageLcdNumber.setSmallDecimalPoint(False)
        self.CurveFittingCoveragePrecentageLcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CurveFittingCoveragePrecentageLcdNumber.setObjectName("CurveFittingCoveragePrecentageLcdNumber")
        self.gridLayout_2.addWidget(self.CurveFittingCoveragePrecentageLcdNumber, 2, 1, 1, 1)
        self.extrapolationPercentageLabel = QtWidgets.QLabel(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.extrapolationPercentageLabel.setFont(font)
        self.extrapolationPercentageLabel.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.extrapolationPercentageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.extrapolationPercentageLabel.setObjectName("extrapolationPercentageLabel")
        self.gridLayout_2.addWidget(self.extrapolationPercentageLabel, 1, 5, 1, 1)
        self.CurveFittingCoveragePrecentageLabel = QtWidgets.QLabel(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.CurveFittingCoveragePrecentageLabel.setFont(font)
        self.CurveFittingCoveragePrecentageLabel.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.CurveFittingCoveragePrecentageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CurveFittingCoveragePrecentageLabel.setObjectName("CurveFittingCoveragePrecentageLabel")
        self.gridLayout_2.addWidget(self.CurveFittingCoveragePrecentageLabel, 2, 0, 1, 1)
        self.precentageLabel = QtWidgets.QLabel(self.mainGraphControlsGroupBox)
        self.precentageLabel.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.precentageLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.precentageLabel.setObjectName("precentageLabel")
        self.gridLayout_2.addWidget(self.precentageLabel, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem6)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.numberOfChunksSpinBox = QtWidgets.QSpinBox(self.mainGraphControlsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberOfChunksSpinBox.sizePolicy().hasHeightForWidth())
        self.numberOfChunksSpinBox.setSizePolicy(sizePolicy)
        self.numberOfChunksSpinBox.setStyleSheet("border-radius: 7px;\n"
"padding: 5px;")
        self.numberOfChunksSpinBox.setMinimum(1)
        self.numberOfChunksSpinBox.setMaximum(20)
        self.numberOfChunksSpinBox.setObjectName("numberOfChunksSpinBox")
        self.gridLayout_3.addWidget(self.numberOfChunksSpinBox, 2, 4, 1, 1)
        self.numberOfChunksLabel = QtWidgets.QLabel(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.numberOfChunksLabel.setFont(font)
        self.numberOfChunksLabel.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.numberOfChunksLabel.setObjectName("numberOfChunksLabel")
        self.gridLayout_3.addWidget(self.numberOfChunksLabel, 1, 4, 1, 1)
        self.overlapLabel = QtWidgets.QLabel(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.overlapLabel.setFont(font)
        self.overlapLabel.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.overlapLabel.setObjectName("overlapLabel")
        self.gridLayout_3.addWidget(self.overlapLabel, 1, 5, 1, 1)
        self.fitPushButton = QtWidgets.QPushButton(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.fitPushButton.setFont(font)
        self.fitPushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(25, 26, 30);\n"
"    border: 1.1px grey;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background-color: rgb(163, 162, 168);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(145, 144, 149);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(118, 118, 112);\n"
"    }")
        self.fitPushButton.setObjectName("fitPushButton")
        self.gridLayout_3.addWidget(self.fitPushButton, 5, 3, 1, 1)
        self.overlappingRadioButton = QtWidgets.QRadioButton(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.overlappingRadioButton.setFont(font)
        self.overlappingRadioButton.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.overlappingRadioButton.setObjectName("overlappingRadioButton")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.overlappingRadioButton)
        self.gridLayout_3.addWidget(self.overlappingRadioButton, 4, 4, 1, 1)
        self.noOverlappingRadioButton = QtWidgets.QRadioButton(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.noOverlappingRadioButton.setFont(font)
        self.noOverlappingRadioButton.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.noOverlappingRadioButton.setObjectName("noOverlappingRadioButton")
        self.buttonGroup_3.addButton(self.noOverlappingRadioButton)
        self.gridLayout_3.addWidget(self.noOverlappingRadioButton, 3, 4, 1, 1)
        self.fittingOrderSpinBox = QtWidgets.QSpinBox(self.mainGraphControlsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fittingOrderSpinBox.sizePolicy().hasHeightForWidth())
        self.fittingOrderSpinBox.setSizePolicy(sizePolicy)
        self.fittingOrderSpinBox.setStyleSheet("border-radius: 7px;\n"
"padding: 5px;")
        self.fittingOrderSpinBox.setMaximum(10)
        self.fittingOrderSpinBox.setObjectName("fittingOrderSpinBox")
        self.gridLayout_3.addWidget(self.fittingOrderSpinBox, 2, 3, 1, 1)
        self.multipleChunksRadioButton = QtWidgets.QRadioButton(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.multipleChunksRadioButton.setFont(font)
        self.multipleChunksRadioButton.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.multipleChunksRadioButton.setObjectName("multipleChunksRadioButton")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.multipleChunksRadioButton)
        self.gridLayout_3.addWidget(self.multipleChunksRadioButton, 4, 3, 1, 1)
        self.oneChunkRadioButton = QtWidgets.QRadioButton(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.oneChunkRadioButton.setFont(font)
        self.oneChunkRadioButton.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.oneChunkRadioButton.setObjectName("oneChunkRadioButton")
        self.buttonGroup_2.addButton(self.oneChunkRadioButton)
        self.gridLayout_3.addWidget(self.oneChunkRadioButton, 3, 3, 1, 1)
        self.polynomialRadioButton = QtWidgets.QRadioButton(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.polynomialRadioButton.setFont(font)
        self.polynomialRadioButton.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.polynomialRadioButton.setObjectName("polynomialRadioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.polynomialRadioButton)
        self.gridLayout_3.addWidget(self.polynomialRadioButton, 1, 1, 1, 1)
        self.cubicRadioButton = QtWidgets.QRadioButton(self.mainGraphControlsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubicRadioButton.sizePolicy().hasHeightForWidth())
        self.cubicRadioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.cubicRadioButton.setFont(font)
        self.cubicRadioButton.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.cubicRadioButton.setObjectName("cubicRadioButton")
        self.buttonGroup.addButton(self.cubicRadioButton)
        self.gridLayout_3.addWidget(self.cubicRadioButton, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.mainGraphControlsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(163, 162, 168);\n"
"color: rgb(25, 26, 30);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.splineRadioButton = QtWidgets.QRadioButton(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.splineRadioButton.setFont(font)
        self.splineRadioButton.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.splineRadioButton.setObjectName("splineRadioButton")
        self.buttonGroup.addButton(self.splineRadioButton)
        self.gridLayout_3.addWidget(self.splineRadioButton, 2, 1, 1, 1)
        self.fullCoverageRadioButton = QtWidgets.QRadioButton(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.fullCoverageRadioButton.setFont(font)
        self.fullCoverageRadioButton.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.fullCoverageRadioButton.setChecked(True)
        self.fullCoverageRadioButton.setObjectName("fullCoverageRadioButton")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.fullCoverageRadioButton)
        self.gridLayout_3.addWidget(self.fullCoverageRadioButton, 4, 5, 1, 1)
        self.overlapSpinBox = QtWidgets.QSpinBox(self.mainGraphControlsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overlapSpinBox.sizePolicy().hasHeightForWidth())
        self.overlapSpinBox.setSizePolicy(sizePolicy)
        self.overlapSpinBox.setStyleSheet("border-radius: 7px;\n"
"padding: 5px;")
        self.overlapSpinBox.setMaximum(25)
        self.overlapSpinBox.setObjectName("overlapSpinBox")
        self.gridLayout_3.addWidget(self.overlapSpinBox, 2, 5, 1, 1)
        self.constantChunkRadioButton = QtWidgets.QRadioButton(self.mainGraphControlsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.constantChunkRadioButton.sizePolicy().hasHeightForWidth())
        self.constantChunkRadioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.constantChunkRadioButton.setFont(font)
        self.constantChunkRadioButton.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.constantChunkRadioButton.setAutoRepeat(False)
        self.constantChunkRadioButton.setObjectName("constantChunkRadioButton")
        self.buttonGroup_4.addButton(self.constantChunkRadioButton)
        self.gridLayout_3.addWidget(self.constantChunkRadioButton, 3, 5, 1, 1)
        self.fittingOrderLabel = QtWidgets.QLabel(self.mainGraphControlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.fittingOrderLabel.setFont(font)
        self.fittingOrderLabel.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.fittingOrderLabel.setObjectName("fittingOrderLabel")
        self.gridLayout_3.addWidget(self.fittingOrderLabel, 1, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout.addWidget(self.mainGraphControlsGroupBox, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1304, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openAction = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openAction.setIcon(icon)
        self.openAction.setObjectName("openAction")
        self.menuFile.addAction(self.openAction)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainGraphLabel.setText(_translate("MainWindow", "Main Graph"))
        self.errorMapControlsGroupBox.setTitle(_translate("MainWindow", "Error map controls"))
        self.xAxisLabel.setText(_translate("MainWindow", "X-axis"))
        self.xAxisComboBox.setItemText(0, _translate("MainWindow", "Choose Axis Parameter"))
        self.xAxisComboBox.setItemText(1, _translate("MainWindow", "Polynomial Order"))
        self.xAxisComboBox.setItemText(2, _translate("MainWindow", "Number of Chunks"))
        self.xAxisComboBox.setItemText(3, _translate("MainWindow", "Overlapping Percentage"))
        self.startAndCancelErrorMapPushButton.setText(_translate("MainWindow", "Start"))
        self.constantParameterLabel.setText(_translate("MainWindow", "Constant Parameter"))
        self.yAxisLabel.setText(_translate("MainWindow", "Y-axis"))
        self.yAxisComboBox.setItemText(0, _translate("MainWindow", "Choose Axis Parameter"))
        self.yAxisComboBox.setItemText(1, _translate("MainWindow", "Polynomial Order"))
        self.yAxisComboBox.setItemText(2, _translate("MainWindow", "Number of Chunks"))
        self.yAxisComboBox.setItemText(3, _translate("MainWindow", "Overlapping Percentage"))
        self.pauseAndResumeErrorMapPushButton.setText(_translate("MainWindow", "Pause"))
        self.mainGraphControlsGroupBox.setTitle(_translate("MainWindow", "Main Graph Controls"))
        self.signalCoveragePrecentageLabel.setText(_translate("MainWindow", "%"))
        self.precentageOfErrorLabel.setText(_translate("MainWindow", "Percentage of Error"))
        self.extrapolationLabel.setText(_translate("MainWindow", "Extrapolation"))
        self.extrapolationPercentageLabel.setText(_translate("MainWindow", "0% Original Signal"))
        self.CurveFittingCoveragePrecentageLabel.setText(_translate("MainWindow", "Signal curve fitting coverage"))
        self.precentageLabel.setText(_translate("MainWindow", "%"))
        self.numberOfChunksLabel.setText(_translate("MainWindow", "Number of chunks"))
        self.overlapLabel.setText(_translate("MainWindow", "Overlapping Percentage"))
        self.fitPushButton.setText(_translate("MainWindow", "Fit"))
        self.overlappingRadioButton.setText(_translate("MainWindow", "Overlapping"))
        self.noOverlappingRadioButton.setText(_translate("MainWindow", "No Overlapping"))
        self.multipleChunksRadioButton.setText(_translate("MainWindow", "Multiple Chunks"))
        self.oneChunkRadioButton.setText(_translate("MainWindow", "One Chunk"))
        self.polynomialRadioButton.setText(_translate("MainWindow", "Polynomial"))
        self.cubicRadioButton.setText(_translate("MainWindow", "Cubic"))
        self.label_2.setText(_translate("MainWindow", "Interpolation Methods"))
        self.splineRadioButton.setText(_translate("MainWindow", "Spline"))
        self.fullCoverageRadioButton.setText(_translate("MainWindow", "Keep 100% signal curve fitting coverage"))
        self.constantChunkRadioButton.setText(_translate("MainWindow", "Keep user input\'s number of chunks constant"))
        self.fittingOrderLabel.setText(_translate("MainWindow", "Fitting order"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.openAction.setText(_translate("MainWindow", "Open"))
        self.openAction.setShortcut(_translate("MainWindow", "Ctrl+O"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
